### ISSUE TITLE
panic: interface conversion: interface {} is nil, not map[string]interface {}

### ISSUE THREAD

**Issue by luisdavim** [kubecost/cost-model#10]
Hi, I'm testing out `cost-model` in a cluster on Azure and it keeps crashing with:
```
2019/04/09 12:54:06 Recording prices...
panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 27 [running]:
github.com/kubecost/cost-model/costmodel.getNormalization(0x0, 0x0, 0xc000413630)
        /app/costmodel/costmodel.go:657 +0x21c
github.com/kubecost/cost-model/costmodel.ComputeCostData(0x1df1560, 0xc000426000, 0xc000448000, 0x1e35560, 0xc0002cb100, 0x1b154a7, 0x2, 0xc000058f30, 0x3, 0x0)
        /app/costmodel/costmodel.go:83 +0x57d
main.(*Accesses).recordPrices.func1(0xc000406ec0)
        /app/main.go:95 +0x3d4
created by main.(*Accesses).recordPrices
        /app/main.go:92 +0x3f
```

**Comment by luisdavim** [comment]
I was looking at the code and I was thinking, have you considered using https://github.com/tidwall/gjson ? it makes dealing with dynamic json so much easy than all those `map[string]interface{}`....

**Comment by luisdavim** [comment]
Probably what you need to do to fix this is to modify the `normalization` query on `/app/costmodel/costmodel.go:74` to use `topk` instead of `max`, something like:
```
topk(1,count_over_time(kube_pod_container_resource_requests_memory_bytes{}[1d]))
```

**Comment by AjayTripathy** [comment]
Hi Luis, sorry this was difficult to debug but thanks for your feedback. I've filed #11 , #12 , and #13 to address your comments. Feel free to weigh in on those issues.

**Comment by luisdavim** [comment]
Thanks
