### ISSUE TITLE
Unable to run the cost model

### ISSUE THREAD

**Issue by itskingori** [kubecost/cost-model#115]
I'm trying to run the cost-model and getting this ...

```console
$ kubectl logs -f deployment.extensions/kubecost-cost-model -c cost-model
I0625 18:57:57.223532       1 main.go:350] Starting cost-model (git commit "88aef90e75772d4a00c76d103ba57cc106b757ea")
I0625 18:58:07.732047       1 main.go:367] Success: retrieved a prometheus config file from: http://prometheus-server.kube-system.svc.cluster.local
I0625 18:58:07.924682       1 main.go:373] Success: retrieved the 'up' query against prometheus at: http://prometheus-server.kube-system.svc.cluster.local
I0625 18:58:08.924842       1 provider.go:374] Found ProviderID starting with "aws", using AWS Provider
I0625 18:58:09.531536       1 awsprovider.go:459] Unable to find params for storageClassName pvc-5cacd650-f97e-11e6-bda3-06430f0df8ba
I0625 18:58:09.531572       1 awsprovider.go:459] Unable to find params for storageClassName pvc-bdf6e91a-fcdc-11e6-bda3-06430f0df8ba
I0625 18:58:09.531592       1 awsprovider.go:459] Unable to find params for storageClassName pvc-ffd7a85d-f820-11e6-bda3-06430f0df8ba
I0625 18:58:09.531602       1 awsprovider.go:471] starting download of "https://pricing.us-east-1.amazonaws.com/offers/v1.0/aws/AmazonEC2/current/index.json", which is quite large ...
I0625 18:58:14.524027       1 awsprovider.go:477] Finished downloading "https://pricing.us-east-1.amazonaws.com/offers/v1.0/aws/AmazonEC2/current/index.json"

I0625 19:18:03.922907       1 awsprovider.go:483] done loading "https://pricing.us-east-1.amazonaws.com/offers/v1.0/aws/AmazonEC2/current/index.json"
I0625 19:18:04.250765       1 awsprovider.go:615] Error downloading spot data AccessDenied: Access Denied
	status code: 403, request id: 35EFF9C569BA302A, host id: zxgrYWDEqznapmZCIp0V+X2DPmxQxzh9zfTjH6AW46sBPeCw9choRQx7v3PnfDzQYv7LF7wY2TI=
I0625 19:18:04.251116       1 main.go:266] Recording prices...
I0625 19:18:07.032776       1 costmodel.go:751] No RAM cost found for us-east-1,m4.xlarge,linux, calculating...
I0625 19:18:07.032834       1 costmodel.go:751] No RAM cost found for us-east-1,r4.4xlarge,linux, calculating...
I0625 19:18:07.032858       1 costmodel.go:751] No RAM cost found for us-east-1,r4.xlarge,linux, calculating...
I0625 19:18:07.032880       1 costmodel.go:751] No RAM cost found for us-east-1,r4.2xlarge,linux, calculating...
I0625 19:18:07.032898       1 costmodel.go:751] No RAM cost found for us-east-1,r4.2xlarge,linux, calculating...
I0625 19:18:07.032919       1 costmodel.go:751] No RAM cost found for us-east-1,r4.xlarge,linux, calculating...
I0625 19:18:07.032938       1 costmodel.go:751] No RAM cost found for us-east-1,r4.xlarge,linux, calculating...
I0625 19:18:07.032957       1 costmodel.go:751] No RAM cost found for us-east-1,r4.xlarge,linux, calculating...
I0625 19:18:07.032974       1 costmodel.go:751] No RAM cost found for us-east-1,r4.xlarge,linux, calculating...
I0625 19:18:07.032996       1 costmodel.go:751] No RAM cost found for us-east-1,r4.2xlarge,linux, calculating...
I0625 19:18:07.033014       1 costmodel.go:751] No RAM cost found for us-east-1,r4.xlarge,linux, calculating...
I0625 19:18:07.033031       1 costmodel.go:751] No RAM cost found for us-east-1,r4.xlarge,linux, calculating...
I0625 19:18:07.033051       1 costmodel.go:751] No RAM cost found for us-east-1,r4.xlarge,linux, calculating...
I0625 19:18:07.033072       1 costmodel.go:751] No RAM cost found for us-east-1,m4.xlarge,linux, calculating...
I0625 19:18:07.033094       1 costmodel.go:751] No RAM cost found for us-east-1,r4.2xlarge,linux, calculating...
I0625 19:18:07.033111       1 costmodel.go:751] No RAM cost found for us-east-1,r4.xlarge,linux, calculating...
I0625 19:18:07.033129       1 costmodel.go:751] No RAM cost found for us-east-1,r4.2xlarge,linux, calculating...
I0625 19:18:07.033146       1 costmodel.go:751] No RAM cost found for us-east-1,r4.2xlarge,linux, calculating...
I0625 19:18:07.033170       1 costmodel.go:751] No RAM cost found for us-east-1,r4.xlarge,linux, calculating...
I0625 19:18:07.033189       1 costmodel.go:751] No RAM cost found for us-east-1,r4.xlarge,linux, calculating...
I0625 19:18:07.033207       1 costmodel.go:751] No RAM cost found for us-east-1,r4.xlarge,linux, calculating...
I0625 19:18:07.033225       1 costmodel.go:751] No RAM cost found for us-east-1,r4.4xlarge,linux, calculating...
I0625 19:18:07.033243       1 costmodel.go:751] No RAM cost found for us-east-1,r4.2xlarge,linux, calculating...
I0625 19:18:07.033260       1 costmodel.go:751] No RAM cost found for us-east-1,m4.xlarge,linux, calculating...
```

That said, a few things to note, I'm:

1. Using an existing Prometheus server.
2. Using an ingress instead of the service but can't connect to it.
3. I used the IAM permissions in the `docs` repository.
4. What are the configuration options? I can see `aws.json` in the source ... am I to create my own? How do I configure it to use my `aws.json`? Are there flags?

**Comment by itskingori** [comment]
Actually, it panics with this error:

```go
panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 72 [running]:
github.com/kubecost/cost-model/costmodel.getPVInfoVector(0x1b1af60, 0xc000edacf0, 0xc00454de00, 0x0, 0x0)
	/app/costmodel/costmodel.go:1346 +0x118a
github.com/kubecost/cost-model/costmodel.ComputeCostData(0x21bd480, 0xc0004a22c0, 0x2233800, 0xc0000d4000, 0x221c020, 0xc00020cd80, 0x1e78e46, 0x2, 0x0, 0x0, ...)
	/app/costmodel/costmodel.go:252 +0x15e2
main.(*Accesses).recordPrices.func1(0xc00018ee00)
	/app/main.go:267 +0x1642
created by main.(*Accesses).recordPrices
	/app/main.go:264 +0x3f
```

So it's in a crashloop ...

```
NAME                                       READY   STATUS             RESTARTS   AGE
pod/kubecost-cost-model-6d964c5489-zpz8v   1/2     CrashLoopBackOff   2          2m33s
```

**Comment by AjayTripathy** [comment]
Thanks for this report-- looking into this.

**Comment by itskingori** [comment]
Thought I'd mention that I tried to get rid of 👇 

```
I0625 19:18:04.250765       1 awsprovider.go:615] Error downloading spot data AccessDenied: Access Denied
	status code: 403, request id: 35EFF9C569BA302A, host id: zxgrYWDEqznapmZCIp0V+X2DPmxQxzh9zfTjH6AW46sBPeCw9choRQx7v3PnfDzQYv7LF7wY2TI=
```

By setting `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` based on this ...

https://github.com/kubecost/cost-model/blob/d2fb1011dbe5bc64efb99c2a0a95430554134776/cloud/awsprovider.go#L37-L38

But that doesn't seem to work despite setting these policies:

* https://github.com/kubecost/docs/blob/master/aws-out-of-cluster.md
* https://github.com/kubecost/docs/blob/master/aws-out-of-cluster.md#iam-policy-explanation

Here's a slightly modified kubernetes file ...

```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: kubecost-cost-model
  namespace: operations
  labels:
    app: kubecost
    role: cost-model
spec:
  selector:
    app: kubecost
    role: cost-model
  ports:
    - name: http
      port: 80
      targetPort: 9003
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubecost-cost-model
  namespace: operations
  labels:
    app: kubecost
    role: cost-model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubecost
      role: cost-model
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kubecost
        role: cost-model
    spec:
      serviceAccountName: kubecost-cost-model
      containers:
        - image: ajaytripathy/kubecost-cost-model:0.1.51
          name: cost-model
          ports:
            - containerPort: 9003
              name: http
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: kubecost-cost-model
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: kubecost-cost-model
                  key: aws_secret_access_key
            - name: AWS_CLUSTER_ID
              value: "<some-value>"
            - name: PROMETHEUS_SERVER_ENDPOINT
              value: "http://prometheus-server.kube-system.svc.cluster.local"
          resources:
            requests:
              cpu: "100m"
              memory: "50Mi"
            limits:
              memory: "500Mi"
              cpu: "1000m"
```

And this is what I get when I try to proxy ...

```console
$ kubectl port-forward pod/kubecost-cost-model-546454b6d8-n728j 9003
Forwarding from 127.0.0.1:9003 -> 9003
Forwarding from [::1]:9003 -> 9003
Handling connection for 9003
E0625 22:03:59.687242   20151 portforward.go:331] an error occurred forwarding 9003 -> 9003: error forwarding port 9003 to pod 3326e13efbf1f76d1feb4a6efebb8658c73e99acbc3f138002160f8680a720cf, uid : exit status 1: 2019/06/25 19:03:59 socat[31564] E connect(5, AF=2 127.0.0.1:9003, 16): Connection refused
```

**Comment by AjayTripathy** [comment]
#116 should have improved logging and stop the panics caused here. You should instead see an error logged there-- can you try latest and see if that has a more detailed error for the GetPVInfoVector function?

**Comment by itskingori** [comment]
Yes, it's better ... looks like it's working ...

```console
$ kubectl logs -f deployment.extensions/kubecost-cost-model -c cost-model
I0626 05:29:49.184885       1 main.go:350] Starting cost-model (git commit "73315dbda9ccae541ccb8189571f09cd10743c16")
I0626 05:29:54.279234       1 main.go:367] Success: retrieved a prometheus config file from: http://prometheus-server.kube-system.svc.cluster.local
I0626 05:29:54.306610       1 main.go:373] Success: retrieved the 'up' query against prometheus at: http://prometheus-server.kube-system.svc.cluster.local
I0626 05:29:54.344882       1 provider.go:374] Found ProviderID starting with "aws", using AWS Provider
I0626 05:29:54.378507       1 awsprovider.go:459] Unable to find params for storageClassName pvc-5cacd650-f97e-11e6-bda3-06430f0df8ba
I0626 05:29:54.378538       1 awsprovider.go:459] Unable to find params for storageClassName pvc-bdf6e91a-fcdc-11e6-bda3-06430f0df8ba
I0626 05:29:54.378550       1 awsprovider.go:459] Unable to find params for storageClassName pvc-ffd7a85d-f820-11e6-bda3-06430f0df8ba
I0626 05:29:54.378558       1 awsprovider.go:471] starting download of "https://pricing.us-east-1.amazonaws.com/offers/v1.0/aws/AmazonEC2/current/index.json", which is quite large ...
I0626 05:29:54.523149       1 awsprovider.go:477] Finished downloading "https://pricing.us-east-1.amazonaws.com/offers/v1.0/aws/AmazonEC2/current/index.json"
I0626 05:30:24.032373       1 awsprovider.go:483] done loading "https://pricing.us-east-1.amazonaws.com/offers/v1.0/aws/AmazonEC2/current/index.json"
I0626 05:30:24.127559       1 awsprovider.go:615] Error downloading spot data AccessDenied: Access Denied
	status code: 403, request id: C80BEC48F2B564DA, host id: 1NH9inskSRRaZTxMZJUMxqqqLDz3nF+OvKzBoC6UwaHzX+XEelOyW0YlWjeEVFb/CB/ChfFGspw=
I0626 05:30:24.127674       1 main.go:266] Recording prices...
I0626 05:30:26.782831       1 costmodel.go:254] Unable to get PV Data: many-to-many matching not allowed: matching labels must be unique on one side
I0626 05:30:26.788013       1 awsprovider.go:359] Persistent Volume pricing not found for us-east-1,
I0626 05:30:26.788038       1 awsprovider.go:359] Persistent Volume pricing not found for us-east-1,
I0626 05:30:26.788048       1 awsprovider.go:359] Persistent Volume pricing not found for us-east-1,
I0626 05:30:26.788057       1 awsprovider.go:359] Persistent Volume pricing not found for us-east-1,
I0626 05:30:26.788065       1 awsprovider.go:359] Persistent Volume pricing not found for us-east-1,
[... LOTS AND LOTS OF THE ABOVE ERROR ...]
```

Looks like progress. Now will be looking into the "Persistent Volume pricing not found for" issue.

**Comment by itskingori** [comment]
I was pursuing Kubecost as a possibility but there's a lot to put together i.e. reports, s3, cloudformation, athena, glue, parquet, lambdas. In addition to that:

1. We don't use Helm.
2. We have our own Prometheus instance that we'd like to re-use.
3. We have our own Grafana deployment that we'd like to re-use.
4. We use spot instances and persistent volumes in our clusters and so we'd like those to be included.

That said, I wasn't able to get rid of this (even after adding permissions to access pricing apis):

```
I0626 05:30:24.127559       1 awsprovider.go:615] Error downloading spot data AccessDenied: Access Denied
	status code: 403, request id: C80BEC48F2B564DA, host id: 1NH9inskSRRaZTxMZJUMxqqqLDz3nF+OvKzBoC6UwaHzX+XEelOyW0YlWjeEVFb/CB/ChfFGspw=
I0626 05:30:24.127674       1 main.go:266] Recording prices...
```

And I couldn't figure out what the issue here was (tried to look through the code):

```
I0626 05:30:26.782831       1 costmodel.go:254] Unable to get PV Data: many-to-many matching not allowed: matching labels must be unique on one side
I0626 05:30:26.788013       1 awsprovider.go:359] Persistent Volume pricing not found for us-east-1,
I0626 05:30:26.788038       1 awsprovider.go:359] Persistent Volume pricing not found for us-east-1,
I0626 05:30:26.788048       1 awsprovider.go:359] Persistent Volume pricing not found for us-east-1,
I0626 05:30:26.788057       1 awsprovider.go:359] Persistent Volume pricing not found for us-east-1,
I0626 05:30:26.788065       1 awsprovider.go:359] Persistent Volume pricing not found for us-east-1,
[... LOTS AND LOTS OF THE ABOVE ERROR ...]
```

Also configuration isn't very clear. Did my best to read through the source to find which environment variables I could set (or flags). Found the `aws.json` file but there isn't much around that (as I asked in https://github.com/kubecost/cost-model/issues/115#issue-460598427):

> What are the configuration options? I can see aws.json in the source ... am I to create my own? How do I configure it to use my aws.json? Are there flags?

Considering this was a spike to quickly see if we can get something up and running ... we will hold off and maybe review it a few months down the line. My collective assessment is that it's quite difficult to get it running i.e. I got it running and can get some data from `/costModel` and `/metrics`, but I couldn't get rid of the errors in the logs (hence I couldn't trust values that could be possibly wrong on spot instances and persistent volumes).

That said, thanks for working on this and taking the time to respond and making even part of it open-source (I know you didn't have to). 🙇

**Comment by dwbrown2** [comment]
I wanted to give this some thought before following up. First, thanks so much for the candid feedback!  

Most of our users are deploying via helm which includes our frontend UI. We've so far invested much more time in those UI paths for managing these integrations. So I agree that there is significant room for improvement when deploying/configuring the cost-model pod directly. These are the immediate opportunities that I see:

1. Better documentation for AWS/GCP key integrations
2. A static manifest so you can deploy our UI with helm/tiller
3. This many-to-many matching appears to be a bug @AjayTripathy 
4. Persistent volume pricing log can be innocuous, so this is potentially too verbose
5. More useful log statements when key access is denied 

Would be great if you have any feedback on these, especially if 2) would be helpful.

**Comment by itskingori** [comment]
> [...] We've so far invested much more time in those UI paths for managing these integrations.

Yes, I noticed! 😅 Had to look hard for the YAML manifests.

> 1. Better documentation for AWS/GCP key integrations

My colleague (@zacblazic) suggested that it's possible we didn't need to follow through the AWS steps as those were for out-of-cluster costs. But that itself wasn't clear to me so I was trying to do it all. When we get some free time we might give it another stab.

> 2. A static manifest so you can deploy our UI with helm/tiller

We don't use Helm/Tiller at all so it's unlikely this will be useful to us since we wouldn't set it up for this one instance.

Lastly noted on point  3, 4 & 5.

FYI: @hadrianvalentine.

**Comment by dwbrown2** [comment]
Oh no, my apologies! 2) was meant to say release a "manifest so you can deploy our UI WITHOUT helm/tiller." Sorry for my mistake. 

Zac was indeed correct that integrating with out-of-cluster costs is optional, but I agree we could state this more explicitly.

**Comment by itskingori** [comment]
@dwbrown2 Noted and thanks.

**Comment by dwbrown2** [comment]
As a first follow up, we have created a [manifest](https://raw.githubusercontent.com/kubecost/cost-analyzer-helm-chart/master/kubecost.yaml) for our UI that avoids installing Tiller. It can be used with the command below, and comes with node-exporter, Prometheus, etc by default: 

`kubectl apply -f https://raw.githubusercontent.com/kubecost/cost-analyzer-helm-chart/master/kubecost.yaml --namespace kubecost`

Node-exporter and Prometheus can be disabled as needed. More updates to come.

**Comment by dwbrown2** [comment]
@AjayTripathy has also improved logging and added a default storage fallback with #124
