### ISSUE TITLE
Cost-model panic occurring in v1.44.4

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/cost-model#174]
At first install this was working for user. After about a week, they began having issues querying their data.

```
[kubecost-cost-analyzer-8558649ffb-45b4l cost-analyzer-frontend] 2019/10/07 18:26:48 [error] 9#9: *347 upstream prematurely closed connection while reading response header from upstream, client: 127.0.0.1, server: _, request: "GET /model/costDataModel?timeWindow=1d HTTP/1.1", upstream: "http://10.230.2.156:9003/costDataModel?timeWindow=1d", host: "localhost:9090", referrer: "http://localhost:9090/overview.html"

[kubecost-cost-analyzer-8558649ffb-45b4l cost-model] goroutine 6288 [running]:

[kubecost-cost-analyzer-8558649ffb-45b4l cost-analyzer-frontend] 127.0.0.1 - - [07/Oct/2019:18:26:48 +0000] "GET /model/costDataModel?timeWindow=1d HTTP/1.1" 502 157 "http://localhost:9090/overview.html" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:69.0) Gecko/20100101 Firefox/69.0" "-"

[kubecost-cost-analyzer-8558649ffb-45b4l cost-model] net/http.(*conn).serve.func1(0xc000722140)

[kubecost-cost-analyzer-8558649ffb-45b4l cost-model] /usr/local/go/src/net/http/server.go:1769 +0x139

[kubecost-cost-analyzer-8558649ffb-45b4l cost-model] panic(0x1cf6cc0, 0xc001a28c30)

[kubecost-cost-analyzer-8558649ffb-45b4l cost-model] /usr/local/go/src/runtime/panic.go:522 +0x1b5

[kubecost-cost-analyzer-8558649ffb-45b4l cost-model] github.com/kubecost/cost-model/costmodel.labelsFromPrometheusQuery(0x1c812a0, 0xc001ff7da0, 0xc0024e4000, 0x20594, 0x1c812a0)

[kubecost-cost-analyzer-8558649ffb-45b4l cost-model] /app/costmodel/costmodel.go:694 +0x988

[kubecost-cost-analyzer-8558649ffb-45b4l cost-model] github.com/kubecost/cost-model/costmodel.findDeletedPodInfo(0x237a300, 0xc0003106c0, 0xc000bc3b98, 0xc0007d494e, 0x2, 0x0, 0x0)

[kubecost-cost-analyzer-8558649ffb-45b4l cost-model] /app/costmodel/costmodel.go:672 +0x356

[kubecost-cost-analyzer-8558649ffb-45b4l cost-model] github.com/kubecost/cost-model/costmodel.(*CostModel).ComputeCostData(0xc000e540a0, 0x237a300, 0xc0003106c0, 0x23f4f20, 0xc000240140, 0x23e2960, 0xc000174070, 0xc0007d494e, 0x2, 0x0, ...)

[kubecost-cost-analyzer-8558649ffb-45b4l cost-model] /app/costmodel/costmodel.go:651 +0x5683

[kubecost-cost-analyzer-8558649ffb-45b4l cost-model] main.(*Accesses).CostDataModel(0xc0000f2820, 0x239cc40, 0xc001c461c0, 0xc00871e400, 0x0, 0x0, 0x0)

[kubecost-cost-analyzer-8558649ffb-45b4l cost-model] /app/main.go:147 +0x412

[kubecost-cost-analyzer-8558649ffb-45b4l cost-model] github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc0014d0000, 0x239cc40, 0xc001c461c0, 0xc00871e400)

[kubecost-cost-analyzer-8558649ffb-45b4l cost-model]                 /go/pkg/mod/github.com/julienschmidt/httprouter@v1.2.0/router.go:334 +0x948

[kubecost-cost-analyzer-8558649ffb-45b4l cost-model] net/http.(*ServeMux).ServeHTTP(0xc0014d0080, 0x239cc40, 0xc001c461c0, 0xc00871e400)

[kubecost-cost-analyzer-8558649ffb-45b4l cost-model] /usr/local/go/src/net/http/server.go:2375 +0x1d6

[kubecost-cost-analyzer-8558649ffb-45b4l cost-model] net/http.serverHandler.ServeHTTP(0xc000aa0340, 0x239cc40, 0xc001c461c0, 0xc00871e400)

[kubecost-cost-analyzer-8558649ffb-45b4l cost-model] /usr/local/go/src/net/http/server.go:2774 +0xa8

[kubecost-cost-analyzer-8558649ffb-45b4l cost-model] net/http.(*conn).serve(0xc000722140, 0x23a4140, 0xc0029e82c0)

[kubecost-cost-analyzer-8558649ffb-45b4l cost-model] /usr/local/go/src/net/http/server.go:1878 +0x851

[kubecost-cost-analyzer-8558649ffb-45b4l cost-model] created by net/http.(*Server).Serve

[kubecost-cost-analyzer-8558649ffb-45b4l cost-model] /usr/local/go/src/net/http/server.go:2884 +0x2f4
```

**Comment by dwbrown2** [comment]
This is now addressed in v.1.45. It was caused by a Prometheus query returning unexpected data. @AjayTripathy can you provide any more details?

**Comment by AjayTripathy** [comment]
Yes, note that the query itself may not be fixed, but the error should be appropriately logged now and the server should not crash. The query isn't essential to computing the cost-model, but some data may be missing for historical tags.
