### ISSUE TITLE
Config file being corrupted during write

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/cost-model#281]
```
I0119 19:52:26.889872       1 provider.go:320] Found ProviderID starting with "aws", using AWS Provider
I0119 19:52:26.893095       1 router.go:830] ERROR UPDATING CONFIG: unexpected end of JSON input
I0119 19:52:26.893299       1 awsprovider.go:483] Error downloading default pricing data: unexpected end of JSON input
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x18bdbb3]

goroutine 1 [running]:
github.com/kubecost/cost-model/cloud.(*AWS).DownloadPricingData(0xc000f78140, 0x0, 0x0)
/app/cost-model/cloud/awsprovider.go:485 +0xd3
github.com/kubecost/cost-model/costmodel.Initialize()
/app/cost-model/costmodel/router.go:998 +0x185f
main.Initialize()
/app/kubecost-cost-model/main.go:422 +0x37
main.main()
/app/kubecost-cost-model/main.go:514 +0x37
```

Reported after report from Wayne

**Comment by dwbrown2** [comment]
https://github.com/kubecost/cost-model/pull/283

**Comment by dwbrown2** [comment]
We added additional safeguards in v1.50.4 to protect against this. Based on everything we have seen this is now resolved.
