### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by bentatham** [kubecost/cost-model#628]
I found kubecost returning 503 in my cluster...

Version: 1.70.1

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1b0f973]

goroutine 526 [running]:
github.com/kubecost/kubecost-cost-model/pkg/provider.(*AWS).QueryCloudAssets.func1(0xc0025c2a80, 0xc001c5e100, 0x0)
	/app/kubecost-cost-model/pkg/provider/aws.go:547 +0x7c3
github.com/aws/aws-sdk-go/service/athena.(*Athena).GetQueryResultsPagesWithContext(0xc00445a9d0, 0x26925c0, 0xc000126040, 0xc0025c2a40, 0xc004f39bb8, 0x0, 0x0, 0x0, 0x0, 0xc0035bc230)
	/go/pkg/mod/github.com/aws/aws-sdk-go@v1.28.9/service/athena/api.go:866 +0x15e
github.com/aws/aws-sdk-go/service/athena.(*Athena).GetQueryResultsPages(...)
	/go/pkg/mod/github.com/aws/aws-sdk-go@v1.28.9/service/athena/api.go:840
github.com/kubecost/kubecost-cost-model/pkg/provider.(*AWS).QueryCloudAssets(0xc0019e8070, 0x0, 0xed74f9580, 0xc001c01ec0, 0x0, 0xed758d000, 0xc001c01ec0, 0x4e94914f0000, 0xc0006eeab0, 0xc000dad2f0, ...)
	/app/kubecost-cost-model/pkg/provider/aws.go:503 +0x1089
main.(*Accesses).RunCloudAssetsPipeline.func1(0x37507e0, 0xc001075c58, 0x5, 0xc0014d40e0)
	/app/kubecost-cost-model/main.go:3110 +0x97f
created by main.(*Accesses).RunCloudAssetsPipeline
	/app/kubecost-cost-model/main.go:3073 +0xb5
```

(From `kubectl -n kubecost logs kubecost-cost-analyzer-5ff7f4677f-mchc9  cost-model`)

**Comment by dwbrown2** [comment]
Thanks, Ben! Niko has a patch and it should be in our build this week.
